In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9925, 9729, 1921, 7227],
 [9925, 9729, 1921, 1476],
 [9925, 6692, 1921, 5324],
 [4235, 3956, 6564, 9768, 8502],
 [4235, 3956, 6564, 9768, 2470],
 [9146, 9925, 2050, 1921, 1406],
 [9606, 7649, 1813, 9768]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9925 9729 1921 7227]
 [   0    0    0    0 9925 9729 1921 1476]
 [   0    0    0    0 9925 6692 1921 5324]
 [   0    0    0 4235 3956 6564 9768 8502]
 [   0    0    0 4235 3956 6564 9768 2470]
 [   0    0    0 9146 9925 2050 1921 1406]
 [   0    0    0    0 9606 7649 1813 9768]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 68ms/step


array([[[-0.00743134,  0.02926404, -0.03101542,  0.04817529,
          0.00201012,  0.0088737 ,  0.01628698,  0.01644179,
          0.0132328 , -0.02321776],
        [-0.00743134,  0.02926404, -0.03101542,  0.04817529,
          0.00201012,  0.0088737 ,  0.01628698,  0.01644179,
          0.0132328 , -0.02321776],
        [-0.00743134,  0.02926404, -0.03101542,  0.04817529,
          0.00201012,  0.0088737 ,  0.01628698,  0.01644179,
          0.0132328 , -0.02321776],
        [-0.00743134,  0.02926404, -0.03101542,  0.04817529,
          0.00201012,  0.0088737 ,  0.01628698,  0.01644179,
          0.0132328 , -0.02321776],
        [ 0.01814923,  0.04004587,  0.01222218,  0.01332572,
          0.04739399, -0.01158193, -0.04775297,  0.03668258,
         -0.01807909,  0.01363808],
        [-0.01050038, -0.03995532, -0.04565148,  0.01088995,
          0.00290662, -0.0151308 ,  0.0053825 , -0.00114669,
         -0.04415066,  0.03637011],
        [-0.03847964,  0.02762374,  0.01343862, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9925, 9729, 1921, 7227], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 17ms/step


array([[-0.00743134,  0.02926404, -0.03101542,  0.04817529,  0.00201012,
         0.0088737 ,  0.01628698,  0.01644179,  0.0132328 , -0.02321776],
       [-0.00743134,  0.02926404, -0.03101542,  0.04817529,  0.00201012,
         0.0088737 ,  0.01628698,  0.01644179,  0.0132328 , -0.02321776],
       [-0.00743134,  0.02926404, -0.03101542,  0.04817529,  0.00201012,
         0.0088737 ,  0.01628698,  0.01644179,  0.0132328 , -0.02321776],
       [-0.00743134,  0.02926404, -0.03101542,  0.04817529,  0.00201012,
         0.0088737 ,  0.01628698,  0.01644179,  0.0132328 , -0.02321776],
       [ 0.01814923,  0.04004587,  0.01222218,  0.01332572,  0.04739399,
        -0.01158193, -0.04775297,  0.03668258, -0.01807909,  0.01363808],
       [-0.01050038, -0.03995532, -0.04565148,  0.01088995,  0.00290662,
        -0.0151308 ,  0.0053825 , -0.00114669, -0.04415066,  0.03637011],
       [-0.03847964,  0.02762374,  0.01343862, -0.04616181, -0.03828036,
        -0.0357651 ,  0.03449848, -0.04728452